# Generated by Django 3.1.5 on 2021-06-17 21:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_key', models.TextField(null=True)),
                ('name_friendly', models.CharField(help_text='A friendly name for the account', max_length=200)),
                ('provider', models.CharField(help_text='Company providing the account', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_key', models.TextField(null=True)),
                ('ref', models.CharField(max_length=250)),
                ('value', models.IntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('is_auto', models.BooleanField(blank=True, default=False)),
                ('comment', models.TextField()),
                ('pay_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='money_planner.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_key', models.TextField(null=True)),
                ('ref', models.CharField(max_length=250)),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_key', models.TextField(null=True)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstanceAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_key', models.TextField(null=True)),
                ('start_balance', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.account')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.instance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_key', models.TextField(null=True)),
                ('date', models.CharField(max_length=10)),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='money_planner.template')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='money_planner.template')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_key', models.TextField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.account')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.template')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_key', models.TextField(null=True)),
                ('ref', models.CharField(max_length=250)),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_key', models.TextField(null=True)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.transfer')),
                ('template_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.templateaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateIncome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_key', models.TextField(null=True)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.income')),
                ('template_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.templateaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_key', models.TextField(null=True)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.expense')),
                ('template_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.templateaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstanceTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_key', models.TextField(null=True)),
                ('instance_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.instanceaccount')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.transfer')),
                ('origin', models.ForeignKey(help_text='The original template that spawned this instance, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='money_planner.templatetransfer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstanceIncome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_key', models.TextField(null=True)),
                ('instance_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.instanceaccount')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.income')),
                ('origin', models.ForeignKey(help_text='The original template that spawned this instance, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='money_planner.templateincome')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstanceExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_key', models.TextField(null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('instance_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.instanceaccount')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_planner.expense')),
                ('origin', models.ForeignKey(help_text='The original template that spawned this instance, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='money_planner.templateexpense')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='instanceaccount',
            name='origin',
            field=models.ForeignKey(help_text='The original template that spawned this instance, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='money_planner.templateaccount'),
        ),
        migrations.AddField(
            model_name='instance',
            name='origin',
            field=models.ForeignKey(help_text='The original template that spawned this instance, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='money_planner.template'),
        ),
    ]
