# Generated by Django 3.1.5 on 2021-01-28 01:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classifier', models.IntegerField(choices=[(None, '(Unknown)'), (0, '(None)'), (1, 'Cash'), (2, 'Credit card'), (3, 'Loan'), (4, 'Investment'), (5, 'Virtual')])),
                ('name_transaction', models.CharField(help_text='Unique name to tie to transactions', max_length=200, unique=True)),
                ('provider', models.CharField(help_text='Company providing the account', max_length=200)),
                ('name_friendly', models.CharField(help_text='A friendly name for the account', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('from_mint', models.BooleanField(default=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_money_details.category_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posted', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('description_from_source', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('post_type', models.IntegerField(choices=[(None, '(Unknown)'), (0, '(None)'), (1, 'Debit'), (2, 'Credit')])),
                ('notes', models.TextField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money_details.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_details.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountCurrentValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posted', models.DateField()),
                ('amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_details.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='money_details.category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='money_details.category')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
            bases=('money_details.category',),
        ),
    ]
