# Generated by Django 3.1.5 on 2021-06-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='origin_key',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='accountcurrentvalue',
            name='origin_key',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='origin_key',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_key',
            field=models.TextField(null=True),
        ),
    ]
